project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "🚀Jump into RSE"
  search: true
  author: "Yinhao Zhan"
  date: "03/24/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - 2+Portfolio+tools.qmd
    - 3+Remote+sensing+data.qmd
    - 4+Policy+applications.qmd
    - 5+Google+Earth+Engine.qmd
    - 6+Classification+I.qmd
    - 7+Classification+II.qmd
    - 8+Temperature+and+policy.qmd
    - 9+Synthetic+Aperture+Radar+(SAR)+data.qmd
    - summary.qmd
    #- references.qmd
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://github.com/Murphy829/RSE/blob/master/RSE.png?raw=true"
    favicon: "https://raw.githubusercontent.com/Murphy829/RSE/master/SUN.ico"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://andrewmaclachlan.github.io/CASA0023/
        text: "CASA00023ModuleBook"
      - icon: github
        href: https://github.com/Murphy829/RSE
        text: "SourceCode"

    style: "docked"
    search: true
    collapse-level: 1


bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

