# Summary

In summary. Here is the reference.





- Ioannides, M., Addison, A., Georgopoulos, A., & Kalisperis, L. THE IMPORTANCE OF CONSIDERING ATMOSPHERIC CORRECTION IN THE PRE-PROCESSING OF SATELLITE REMOTE SENSING DATA INTENDED FOR THE MANAGEMENT AND DETECTION OF CULTURAL SITES: A CASE STUDY OF THE CYPRUS AREA.[🔗](
https://www.researchgate.net/profile/Kyriacos-Themistocleous/publication/257067491_The_importance_of_considering_atmospheric_correction_in_the_pre-processing_of_satellite_remote_sensing_data_intended_for_the_management_and_detection_of_cultural_sites_a_case_study_of_the_Cyprus_area/links/57ffcf0108ae6fc7fc6523f0/The-importance-of-considering-atmospheric-correction-in-the-pre-processing-of-satellite-remote-sensing-data-intended-for-the-management-and-detection-of-cultural-sites-a-case-study-of-the-Cyprus-area.pdf)



- Martínez, L., Arbiol, R., Palà, V., & Pérez, F. (2007, July). Digital Metric Camera radiometric and colorimetric calibration with simultaneous CASI imagery to a CIE Standard Observer based colour space. In 2007 IEEE International Geoscience and Remote Sensing Symposium (pp. 4140-4143). IEEE.
 [🔗](https://www.researchgate.net/publication/224301411_Digital_metric_camera_radiometric_and_colorimetric_calibration_with_simultaneous_CASI_imagery_to_a_CIE_standard_observer_based_colour_space)

- Haldar, S. K. (2018). Photogeology, remote sensing and geographic information system in mineral exploration. In Mineral Exploration (pp. 47-68). Elsevier.[🔗](https://www.sciencedirect.com/science/article/pii/B9780124160057000064)



- Hadjimitsis, D. G., Papadavid, G., Agapiou, A., Themistocleous, K., Hadjimitsis, M. G., Retalis, A., ... & Clayton, C. R. I. (2010). Atmospheric correction for satellite remotely sensed data intended for agricultural applications: impact on vegetation indices. Natural Hazards and Earth System Sciences, 10(1), 89-95.[🔗](https://nhess.copernicus.org/articles/10/89/2010/)



- Alesheikh, A. A., Ghorbanali, A., & Nouri, N. (2007). Coastline change detection using remote sensing. International Journal of Environmental Science & Technology, 4, 61-66.[🔗](https://link.springer.com/article/10.1007/BF03325962)



- Bao, H., Ming, D., Guo, Y., Zhang, K., Zhou, K., & Du, S. (2020). DFCNN-based semantic recognition of urban functional zones by integrating remote sensing data and POI data. Remote Sensing, 12(7), 1088.[🔗](https://www.mdpi.com/2072-4292/12/7/1088)







- Chen, C., Deng, J., & Lv, N. (2020, August). Illegal Constructions Detection in Remote Sensing Images based on Multi-scale Semantic Segmentation. In 2020 IEEE International Conference on Smart Internet of Things (SmartIoT) (pp. 300-303). IEEE.[🔗](https://ieeexplore.ieee.org/document/9191992)




- Zhang, F., Nauata, N., & Furukawa, Y. (2020). Conv-mpn: Convolutional message passing neural network for structured outdoor architecture reconstruction. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 2798-2807).[🔗](https://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Conv-MPN_Convolutional_Message_Passing_Neural_Network_for_Structured_Outdoor_Architecture_CVPR_2020_paper.html)





- Zhang, Z., Liu, F., Zhao, X., Wang, X., Shi, L., Xu, J., ... & Liu, B. (2018). Urban expansion in China based on remote sensing technology: a review. Chinese Geographical Science, 28, 727-743.[🔗](https://link.springer.com/article/10.1007/s11769-018-0988-9)




- Yeh, C., Perez, A., Driscoll, A., Azzari, G., Tang, Z., Lobell, D., ... & Burke, M. (2020). Using publicly available satellite imagery and deep learning to understand economic well-being in Africa. Nature communications, 11(1), 2583.[🔗](https://www.nature.com/articles/s41467-020-16185-w)




- Jean, N., Burke, M., Xie, M., Davis, W. M., Lobell, D. B., & Ermon, S. (2016). Combining satellite imagery and machine learning to predict poverty. Science, 353(6301), 790-794.[🔗](https://www.science.org/doi/full/10.1126/science.aaf7894)



- Pokhriyal, N., & Jacques, D. C. (2017). Combining disparate data sources for improved poverty prediction and mapping. Proceedings of the National Academy of Sciences, 114(46), E9783-E9792.[🔗](
https://www.pnas.org/doi/abs/10.1073/pnas.1700319114)



- Tamiminia, H., Salehi, B., Mahdianpari, M., Quackenbush, L., Adeli, S., & Brisco, B. (2020). Google Earth Engine for geo-big data applications: A meta-analysis and systematic review. ISPRS Journal of Photogrammetry and Remote Sensing, 164, 152-170.[🔗](https://www.sciencedirect.com/science/article/pii/S0924271620300927)




- Zhao, Q., Yu, L., Li, X., Peng, D., Zhang, Y., & Gong, P. (2021). Progress and trends in the application of Google Earth and Google Earth Engine. Remote Sensing, 13(18), 3778.[🔗](https://www.mdpi.com/2072-4292/13/18/3778)



- Macchiarulo, V., Milillo, P., Blenkinsopp, C., Reale, C., & Giardina, G. (2022, January). Multi-temporal InSAR for transport infrastructure monitoring: recent trends and challenges. In Proceedings of the Institution of Civil Engineers-Bridge Engineering (pp. 1-26). Thomas Telford Ltd.[🔗](https://www.researchgate.net/publication/356791826_Multi-Temporal_InSAR_for_transport_infrastructure_monitoring_Recent_trends_and_challenges)




- Grippa, T., Lennert, M., Beaumont, B., Vanhuysse, S., Stephenne, N., & Wolff, E. (2017). An open-source semi-automated processing chain for urban object-based classification. Remote Sensing, 9(4), 358.[🔗](https://www.mdpi.com/2072-4292/9/4/358#)
